// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class TesterDB {
  static entity = "TesterDB";
  static schema = {
    id: { type: "String", index: true },
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

import { String } from "@blockflow-labs/utils";

export interface ITesterDB extends Document {
  id: String;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}
