export const userSchema = {
  cctpYearDataDB: [
    { name: "id", type: "String" },
    { name: "year", type: "string" },
    { name: "txCount", type: "string" },
    { name: "yearlyVolume", type: "string" },
    { name: "deposited", type: "string" },
    { name: "withdrawal", type: "string" },
    { name: "totalFee", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  cctpAllTimeDB: [
    { name: "id", type: "String" },
    { name: "txCount", type: "string" },
    { name: "allTimeVolume", type: "string" },
    { name: "deposited", type: "string" },
    { name: "withdrawal", type: "string" },
    { name: "totalFee", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  burnTransactionsTable: [
    { name: "id", type: "String" },
    { name: "transactionHash", type: "string" },
    { name: "sourceDomain", type: "string" },
    { name: "destinationDomain", type: "string" },
    { name: "amount", type: "number" },
    { name: "mintRecipient", type: "string" },
    { name: "messageSender", type: "string" },
    { name: "timeStamp", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  cctpMonthDataDB: [
    { name: "id", type: "String" },
    { name: "month", type: "string" },
    { name: "txCount", type: "string" },
    { name: "monthlyVolume", type: "string" },
    { name: "deposited", type: "string" },
    { name: "withdrawal", type: "string" },
    { name: "totalFee", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  mintTransactionsTable: [
    { name: "id", type: "String" },
    { name: "transactionHash", type: "string" },
    { name: "sourceDomain", type: "string" },
    { name: "destinationDomain", type: "string" },
    { name: "amount", type: "number" },
    { name: "mintRecipient", type: "string" },
    { name: "timeStamp", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  FeeInfo: [
    { name: "id", type: "String" },
    { name: "feeInUSDC", type: "number" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  DomainsTable: [
    { name: "id", type: "String" },
    { name: "domainName", type: "string" },
    { name: "chainId", type: "String" },
    { name: "tokenAddress", type: "string" },
    { name: "permessageburnlimit", type: "number" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  attestationTable: [
    { name: "id", type: "String" },
    { name: "attestationHash", type: "string" },
    { name: "messageHash", type: "string" },
    { name: "timeStamp", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  cctpWeekDataDB: [
    { name: "id", type: "String" },
    { name: "week", type: "string" },
    { name: "txCount", type: "string" },
    { name: "weeklyVolume", type: "string" },
    { name: "deposited", type: "string" },
    { name: "withdrawal", type: "string" },
    { name: "totalFee", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
  cctpDayDataDB: [
    { name: "id", type: "String" },
    { name: "date", type: "string" },
    { name: "txCount", type: "string" },
    { name: "dailyVolume", type: "string" },
    { name: "deposited", type: "string" },
    { name: "withdrawal", type: "string" },
    { name: "totalFee", type: "string" },
    { name: "entityId", type: "String" },
    { name: "blocknumber", type: "Number" },
    { name: "chainId", type: "String" },
    { name: "instanceId", type: "String" },
    { name: "_id", type: "ObjectId" },
  ],
};
